[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# این بخش، ربات خبرنگار ما را هر ساعت یک بار اجرا می کند
[functions.generate-news]
  schedule = "0 * * * *"
